CREATE TYPE "OrganizationType" AS ENUM (
  'GOVERNMENT_AGENCY',
  'RESEARCH_INSTITUTION',
  'NGO',
  'COMMUNITY_GROUP',
  'PRIVATE_COMPANY',
  'INTERNATIONAL_ORG',
  'OTHER'
);

ALTER TABLE "Organization"
  ALTER COLUMN "type" TYPE "OrganizationType"
  USING (
    CASE "type"::text
      WHEN 'GOVERNMENT_AGENCY' THEN 'GOVERNMENT_AGENCY'
      WHEN 'RESEARCH_INSTITUTION' THEN 'RESEARCH_INSTITUTION'
      WHEN 'NGO' THEN 'NGO'
      WHEN 'INTERNATIONAL_ORG' THEN 'INTERNATIONAL_ORG'
      WHEN 'CITIZEN_SCIENCE' THEN 'COMMUNITY_GROUP'
      ELSE 'OTHER'
    END
  )::"OrganizationType";
