-- AlterTable
ALTER TABLE "District" ADD COLUMN     "avgCloudCover30d" DOUBLE PRECISION,
ADD COLUMN     "avgHumidity30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm10_30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm25_30d" DOUBLE PRECISION,
ADD COLUMN     "avgTemp30d" DOUBLE PRECISION,
ADD COLUMN     "avgUvIndex30d" DOUBLE PRECISION,
ADD COLUMN     "avgWindSpeed30d" DOUBLE PRECISION,
ADD COLUMN     "climateUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "maxTemp30d" DOUBLE PRECISION,
ADD COLUMN     "minTemp30d" DOUBLE PRECISION,
ADD COLUMN     "totalPrecip30d" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Division" ADD COLUMN     "avgCloudCover30d" DOUBLE PRECISION,
ADD COLUMN     "avgHumidity30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm10_30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm25_30d" DOUBLE PRECISION,
ADD COLUMN     "avgTemp30d" DOUBLE PRECISION,
ADD COLUMN     "avgUvIndex30d" DOUBLE PRECISION,
ADD COLUMN     "avgWindSpeed30d" DOUBLE PRECISION,
ADD COLUMN     "climateUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "maxTemp30d" DOUBLE PRECISION,
ADD COLUMN     "minTemp30d" DOUBLE PRECISION,
ADD COLUMN     "totalPrecip30d" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Union" ADD COLUMN     "avgCloudCover30d" DOUBLE PRECISION,
ADD COLUMN     "avgHumidity30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm10_30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm25_30d" DOUBLE PRECISION,
ADD COLUMN     "avgTemp30d" DOUBLE PRECISION,
ADD COLUMN     "avgUvIndex30d" DOUBLE PRECISION,
ADD COLUMN     "avgWindSpeed30d" DOUBLE PRECISION,
ADD COLUMN     "climateUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "maxTemp30d" DOUBLE PRECISION,
ADD COLUMN     "minTemp30d" DOUBLE PRECISION,
ADD COLUMN     "totalPrecip30d" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Upazila" ADD COLUMN     "avgCloudCover30d" DOUBLE PRECISION,
ADD COLUMN     "avgHumidity30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm10_30d" DOUBLE PRECISION,
ADD COLUMN     "avgPm25_30d" DOUBLE PRECISION,
ADD COLUMN     "avgTemp30d" DOUBLE PRECISION,
ADD COLUMN     "avgUvIndex30d" DOUBLE PRECISION,
ADD COLUMN     "avgWindSpeed30d" DOUBLE PRECISION,
ADD COLUMN     "climateUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "maxTemp30d" DOUBLE PRECISION,
ADD COLUMN     "minTemp30d" DOUBLE PRECISION,
ADD COLUMN     "totalPrecip30d" DOUBLE PRECISION;

-- CreateTable
CREATE TABLE "UnionDailyClimate" (
    "id" TEXT NOT NULL,
    "unionId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "avgTemp" DOUBLE PRECISION,
    "minTemp" DOUBLE PRECISION,
    "maxTemp" DOUBLE PRECISION,
    "avgHumidity" DOUBLE PRECISION,
    "totalPrecip" DOUBLE PRECISION,
    "avgWindSpeed" DOUBLE PRECISION,
    "maxWindSpeed" DOUBLE PRECISION,
    "avgCloudCover" DOUBLE PRECISION,
    "avgPm25" DOUBLE PRECISION,
    "avgPm10" DOUBLE PRECISION,
    "avgUvIndex" DOUBLE PRECISION,
    "avgOzone" DOUBLE PRECISION,
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UnionDailyClimate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "UnionDailyClimate_unionId_idx" ON "UnionDailyClimate"("unionId");

-- CreateIndex
CREATE INDEX "UnionDailyClimate_date_idx" ON "UnionDailyClimate"("date");

-- CreateIndex
CREATE UNIQUE INDEX "UnionDailyClimate_unionId_date_key" ON "UnionDailyClimate"("unionId", "date");

-- AddForeignKey
ALTER TABLE "UnionDailyClimate" ADD CONSTRAINT "UnionDailyClimate_unionId_fkey" FOREIGN KEY ("unionId") REFERENCES "Union"("id") ON DELETE CASCADE ON UPDATE CASCADE;
